//  FeatureFlags.swift
//  miPic
//  Copyright © 2018 miPic. All rights reserved.
//
//  -------- DO NOT EDIT THIS FILE!!! --------
//  This code is auto-generated
//  To make changes: 
//  1. Update the main.swift file in scripts/FeatureFlagsGen
//  2. Then run 'main.swift' in that folder.
//  ------------------------------------------

import Foundation

enum FeatureVariable: String {
    case featureA
    case featureB
}

protocol FeatureFlagManager {
    func string(for key: String) -> String
    func bool(for key: String) -> Bool
    func int(for key: String) -> Int
    func double(for key: String) -> Double
}

class FeatureFlags {
    let featureFlagManager: FeatureFlagManager

    init(featureFlagManager: FeatureFlagManager) {
        self.featureFlagManager = featureFlagManager
    }

    var featureA: Bool {
        featureFlagManager.bool(for: FeatureVariable.featureA.rawValue)
    }

    var featureB: String {
        featureFlagManager.string(for: FeatureVariable.featureB.rawValue)
    }
}
